### ISSUE TITLE
java.lang.NoClassDefFoundError: org/vafer/jdeb/Console

### ISSUE THREAD

**Issue by justinpitts** [softwaremill/gcp-goodies#1]
I'm on OSX with sbt 1.3.2 installed. When I try to `sbt test` this project, I get thatNoClassDef error. It is mentioned [here](https://github.com/sbt/sbt-native-packager/issues/1053) as being related to coursier, which of course by 1.3.2 is a fairly major part of SBT. 

If I update [this](https://github.com/softwaremill/gcp-goodies/blob/c9ddbe119e0920d6b699b9360b8f6a1e908227ac/part-5/play-scala-stackdriver-logging/project/build.properties#L1) to 1.3.2, the problem goes away for me.

Thanks for the blog writeups - this is very useful stuff.

**Comment by softberries** [comment]
Great! Thanks for the input!
